### ISSUE TITLE
When is metadata.json read ?

### ISSUE THREAD

**Issue by gliatti** [neha01/nft-demo#1]
Hi Neha,

I found your project on youtube and was not able to see where and how the metadata.json file was read by your application.

Is the api of pinata accept either an image file or a json file ? Could make sense

Thanks

**Comment by neha01** [comment]
Hi Robin,

Yes, Pinata API accepts a metadata file.
You can find it here: https://github.com/neha01/nft-demo/blob/master/scripts/runScript.js#L5
I'm reusing the same function to first upload image & then metadata file. So that's why it is commented out.

**Comment by gliatti** [comment]
Yes now I understand better.
Thanks to your example I made my little helper in python https://github.com/robinportigliatti/web3_helper
